### ISSUE TITLE
Add `--output-dir` functionality

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#134]
To allow all output to be generated in the `--output-dir={dir}` location.

**Comment by ronaldtse** [comment]
This means all the derived output:
* MN XML
* other rendered formats HTML/PDF/RXL/DOC
* error output: `.err`

should all be created in this output dir.

**Comment by ronaldtse** [comment]
@abunashir would you have time for this after fontist? Thanks!

**Comment by andrew2net** [comment]
> * error output: `.err`

@ronaldtse the `metanorma` using `metanorma-*` flavor gem's Processor to make an `Asciidoctor::Document` and the asciidostor document using backend (flavor gem) to convert the document. The flavor gems depend on the `metanorma-standoc`, which takes a dir from the asciidostor document filename and writes `*.err` file to the dir.
To change dir for `*.err` file we need update all flavor gems, put output-dir into some attribute of the asciidoctor document and using the attribute as a dir in the backend to save the `*.err`.
It's quite a big job. do we really need it?

**Comment by ronaldtse** [comment]
The motivation for changing the output directory is that sometimes the input directory is not writable. Even if we can copy out the file for compilation, if the input file contains multiple includes, it becomes very tricky.

Maybe @opoudjis can give some hint on how to achieve this in a simpler way?

**Comment by opoudjis** [comment]
There is a very simple solution to this, which harnesses something already put in place.

`@localdir` is there to address the fact that, if asciidoctor is invoked from a directory other than the directory the file is in, the path of the directory can be added to any files output. It is populated through the input file, and is (or should be!) used for all output files, so that they are in the same directory as the input file. That includes the error file. 

The code change would be simply to pass in an argument (somehow) into the call to asciidoctor via metanorma-standoc and its inheritors, which would override the population of `@localdir`.

**Comment by ronaldtse** [comment]
Thanks @opoudjis ! @andrew2net hope this is sufficient for you.

**Comment by andrew2net** [comment]
> The code change would be simply to pass in an argument (somehow) into the call to asciidoctor via metanorma-standoc and its inheritors, which would override the population of `@localdir`.

@opoudjis I see the only way to pass the argument into the call to asciidoctor is adding it to the `Processor#input_to_isodoc` method. But we have to update the method in all metanorma-* flavor gems. Ronald's question was if there is a more simple way. Looks like there isn't
