### ISSUE TITLE
(URGENT) Metanorma `convert` command

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#261]
We need to have the `convert` command to do this:

1. Convert NISO STS XML to Metanorma ADoc
2. Convert ISOSTS XML to Metanorma ADoc

Probably also:
3. Convert RFC XML to Metanorma ADoc

@Intelligent2013 any other functionality we need to expose from mnconvert?

**Comment by ronaldtse** [comment]
This is necessary for https://github.com/paneron/extension-hls/issues/61

**Comment by Intelligent2013** [comment]
> any other functionality we need to expose from mnconvert?

@ronaldtse I think no. All 3 tasks (niso sts, iso sts and rfc) cover possible conversion functionality from xml to adoc.
May be we need some optional parameter to the `convert` command - `output-format` (value `adoc` by default) for further conversion from metanorma xml to sts xml.

**Comment by CAMOBAP** [comment]
@Intelligent2013 @ronaldtse to be on the same page:

1. Do we need explicitly specify input format?
2. Can you suggest some minimal xmls for tests?
3. Is there any other options required for font managment or anything else?

**Comment by Intelligent2013** [comment]
> @Intelligent2013 @ronaldtse to be on the same page:
> 
>     1. Do we need explicitly specify input format?

@CAMOBAP 

mnconvert determines automatically input format:
- if root xml element is `rfc`, then RFC
- if root xml element ends with `-standard` or `metanorma-collection`, then Metanorma (actual for MN xml ->STS conversion)
- otherwise - STS xml (both ISO and NISO)

so no need to specify input format.

>     2. Can you suggest some minimal xmls for tests?

- RFC xml: https://github.com/metanorma/mnconvert/blob/main/src/test/resources/rfc/rfc8650.xml
- STS xml: https://github.com/metanorma/mnconvert/blob/main/src/test/resources/rice-en.final.sts.xml

>     3. Is there any other options required for font managment or anything else?

- optional parameter `--imagesdir <arg>` (folder with images (default value 'images' in mnconvert))
- optional parameter `--output <arg>` (output file path, by default adoc will be created in the input file's folder)

**Comment by ronaldtse** [comment]
Agree with @Intelligent2013 , thanks!

**Comment by CAMOBAP** [comment]
In progress

**Comment by CAMOBAP** [comment]
@ronaldtse PRs are ready for review:
 - https://github.com/metanorma/mnconvert-ruby/pull/2
 - https://github.com/metanorma/metanorma-iso/pull/557
 - https://github.com/metanorma/metanorma-cli/pull/262

**Comment by CAMOBAP** [comment]
merged and released

**Comment by wkwong-ribose** [comment]
Thanks for adding the convert capability in Metanorma.
I want to test the convert function but don't know how to use it.

I installed Metanorma using ```brew install metanorma/metanorma/metanorma```. 
The version shown is still 1.5.2
<img width="281" alt="Screen Shot 2021-12-06 at 2 51 50 PM" src="https://user-images.githubusercontent.com/80878223/144800876-e48b05c1-a059-4791-a03a-be4e621e93be.png">

Is there any documentation about the convert function somewhere?

**Comment by ronaldtse** [comment]
@wkwong-ribose I believe the convert command only came in at 1.5.3, but that version is still not published at [packed-mn](https://github.com/metanorma/packed-mn).

@CAMOBAP can you please help? Thanks.
