### ISSUE TITLE
(URGENT) Bump release version due to crashing bug in relaton-iec, relaton-ogc and relaton-w3c

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#275]
Under certain conditions, relaton-iec, relaton-ogc and relaton-w3c will crash and fail to return, causing a halt in the Metanorma compilation process. These bugs have been fixed and released.

Specifically,
* When the authoritative site is not available
* When the index does not contain a sought item
* When the item is not found on the authoritative site

@CAMOBAP can you please help bump version and release the updated downstream items? Thanks!

**Comment by ronaldtse** [comment]
FYI @gbuehler.

**Comment by CAMOBAP** [comment]
Summary:

1. docker released - https://github.com/metanorma/metanorma-docker/actions/runs/2229313471
2. private docker on the way (restarted) https://github.com/metanorma/metanorma-docker-private/actions/runs/2230898206
3. packed-mn still on the way (restarted) https://github.com/metanorma/packed-mn/actions/runs/2225246816

Point to discuss:
 - docker release will fail if we use versions like  `v1.5.15pre1` because they don't conform semver.org's format. To confirm it should be `v1.5.15-pre.1`

@ronaldtse @opoudjis to be honest I more like formats like `v1.5.15pre1` for our gems, so I propose to write a simple converter step on docker's side, how do you think about this?

**Comment by ronaldtse** [comment]
> to be honest I more like formats like v1.5.15pre1 for our gems, so I propose to write a simple converter step on docker's side, how do you think about this?

I agree!

Thank you very much for getting the release working!
