### ISSUE TITLE
Add usages documentation

### ISSUE THREAD

**Issue by abunashir** [metanorma/metanorma-cli#45]
Comment from @ronaldtse in #43 

While functionality wise this PR is good to go, we still need to get AppVeyor passing because Windows is crucial here.

Can you also help add/update the README to indicate how to use the functionality? Thanks!

How to use a default template repository
How to use a custom template repository (i.e. NIST at GitLab)
How to see what templates are supported by a repository

**Comment by ronaldtse** [comment]
Thanks @abunashir for moving this here!

**Comment by opoudjis** [comment]
cc @ronaldtse. 

I've just realised that the new metanorma-cli, which I was asked to release, has a CLI that is not backward compatible, and that the change is not publicly documented.

The fact that there is an (undocumented) setenv workaround is not a mitigation; it is, after all, undocumented. Nor is the fact that the change in the CLI is the addition of one word (presumably).

This is live software. Breaking live software (and the main interface into using that software at that)  is irresponsible. And this is a syndrome of the eternal fixing things that ain't broke, that the Metanorma project has been plagued with since its inception.

I should not have to mistrust gem releases: I should have been warned explicitly that this change broke backward compatibilty. And my local rspec testing was not going to catch this, because I have to test the gems in a dependency sequence, and metanorma-cli is at the end of the dependency chain.

There is extensive documentation of how to run the Metanorma executable at https://github.com/metanorma/metanorma/blob/master/README.adoc, which @abunashir will need to update. (It should not move to metanorma from metanorma-cli, because metanorma is the natural place for people to find the README.) In addition, this documentation must indicate how to transition from the old functionality to the new. And given that this is live software used in active trials, it is urgent for the documentation to be updated: alternatively, I will have to yank the gem until it is.

Again: this is now live software being used by external agencies, with whom we do not have clear communication channels. Existing CLI must remain backward compatible unless there is a compelling reason not to (which this was not, frankly: the script could easily have detected that there was no second command after "metanorma" and switched to the old method, instead of looking for a setenv.) And changes must not be published unless the public documentation affected is also updated first.

**Comment by ronaldtse** [comment]
@abunashir for this question: "How to see what templates are supported by a repository"

I think we need to implement actual functionality.
