### ISSUE TITLE
URGENT: do not include enterprise flavors in default installation

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#70]
Report from https://github.com/metanorma/homebrew-metanorma/issues/15 :

A Homebrew default install shows a dependency error:
```
/Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/resolver.rb:231:in `search_for': Unable to resolve dependency: 'metanorma-mpfd (~> 0.1.0)' requires 'metanorma-standoc (~> 1.1.0)' (Gem::UnsatisfiableDependencyError)
```

@opoudjis We need to ensure all dependencies are satisfied. The enterprise gems, `mpfd` and `ribose` flavors should not be included in the default installation and therefore should be removed from `metanorma-cli.gemspec`.

**Comment by opoudjis** [comment]
Which are the enterprise gems? Which are the ribose flavours? Why exactly should they not be included? You need to give me more to work on than this.

**Comment by ronaldtse** [comment]
Right now mpfd and ribose are non-SDO gems. Maybe we should just call these “private” gems?

**Comment by opoudjis** [comment]
By Ribose, do you mean rsd?

**Comment by ronaldtse** [comment]
Yes.

**Comment by opoudjis** [comment]
I am pushing a version of metanorma-cli without the MPFD and RSD gems in the gemspec. And since I am convinced this is not going to fix the issue, https://github.com/metanorma/homebrew-metanorma/issues/15 must remain open. I will certainly not push an updated metanorma-cli gem until this has been further investigated.
